version: "3.8"
services:
  api:
    image: 'everfit-demo-api:latest'
    volumes:
      - .:/app
      - /app/node_modules
    container_name: everfit-api
    command: "sh run.sh"
    build:
      context: .
    env_file:
      - ./.env
    ports:
      - 3000:3000
    links:
      - redis
      - mongo
    depends_on:
      - redis
      - mongo
  
  mongo:
    container_name: everfit-mongodb
    image: "mongo"
    ports:
      - 27017:27017

  redis:
    container_name: everfit-redis
    image: "redis:4.0.11"
    ports:
      - 6379:6379
